### PR TITLE
add munge to mvapich plugin

### PR DESCRIPTION
**Pull request by adammoody**

### CODE REVIEW

**Comment by grondo** [comment]
Just a couple quick, minor notes:
1. fatal() will cause immediate termination of srun (IIRC). Where fatal is used here, did you mean error() (since the code assumes it will continue)
2. pmgr_strdupf() might be redundant. Is there any way to use the built-in SLURM string functions? (xstrfmtcat() perhaps?) If you have good reason for pmgr_strdupf() you can ignore my comments.
3. It was confusing to me at first why munge string (mvi->munge) was freed outside mvapich_info_destroy(). It appears that the munge string itself is only needed within mvapich_authenticate_munge(). If so, maybe it would be clearer if the munge string and mungelen are kept private to that function. Then it won't be confusing why those values are never initialized in mvapich_info object. Either way, the comments are good, but a note about why munge string is freed early would be recommended at least.

**Comment by adammoody** [comment]
Regarding #1 and #2, I was hoping to have someone with more experience to help me "slurmify" the new code, i.e., make sure I'm using all of the proper slurm built-in functions where I can.  Can you take a closer look?  I've also got a TODO or two to check.

We could free the mvi->munge string in mvapich_info_destroy, so that we handle mungelen/munge just like it currently handles pidlen/pid.  I decided to free it earlier to conserve memory, rather than accumulating the buffers until we've handled each process.  However, since this protocol is only used for smaller process counts, it shouldn't be a huge amount of memory if wait to free it in mvapich_info_destroy.  The buffers are around 200 bytes, and I currently only use this protocol for process counts of 1024 or less.

We could also keep the state local to the function, say in a static variable, but we'd need to allocate an array of them (one for each process), and then free the array after we've handled the last process.  This would clean the code up in one sense, but I think the extra bookkeeping would complicate it in a different way.

**Comment by grondo** [comment]
Ok, great. For any fatal() call in the new code I would replace it with an error() and make sure this leads to eventual clean exit of srun (by making the mvapich init phase error out). I'm not sure how this works in other parts of the code, I'll have to look at it again.

Take a look at xstrfmtcat and see if it will allow you to remove pmgr_strdupf()
It might not be as nice to use, but better than having similar code duplicated...

For the mvi->munge string, I'm sorry I didn't realize that mvapich_authenticate_munge() might be called multiple times to read the entire munge string. In this case I think the way you did it is simplest, and maybe just add a comment that munge string is being freed early because it is no longer needed to avoid future confusion.

**Comment by adammoody** [comment]
I changed all "fatal" to "error" except for two, which felt like true fatals.  I found xstrdup_printf to replace my custom pmgr_strdupf, and I added the comment about the munge.

**Comment by grondo** [comment]
Thanks! 
Don, ok to merge Adam's stuff?

**Comment by lipari** [comment]
Yes.  Afraid I took the rest of the week off starting today.  I'll be
logging in Thursday am and can work on this if you'd like.
Don

**Pull request merged**
