### PR TITLE
Prevent opaque ncurses WINDOW struct on OS X 10.6.

### PR DESCRIPTION
**Pull request by bringhurst**
Here's another one to work towards things compiling on osx. This might also apply to other systems that might set this as the default, but google doesn't seem to give any examples, so I just wrapped it in the **APPLE** for now.

Just an fyi, I'm running Mac OS X 10.6.7 (Darwin xxxx 10.7.0 Darwin Kernel Version 10.7.0: Sat Jan 29 15:16:10 PST 2011; root:xnu-1504.9.37~1/RELEASE_X86_64 x86_64).

### CODE REVIEW

**Comment by dannyauble** [comment]
Thanks Jon, I was waiting for this one ;).

**Comment by bringhurst** [comment]
After this fix, the code itself compiles without a problem. There's still a weird bug in the config/make that prevents compile unless you specify a target of 10.5, still trying to track that one down. :)

**Comment by dannyauble** [comment]
Cool, so no problems with the priority/multifactor plugin?  I wonder what the guy from yesterday was seeing (http://groups.google.com/group/slurm-devel/browse_thread/thread/4e66349dbc061a47)?  Let us know what you find.  I'll merge these changes into 2.2 as well.

Thanks

**Comment by bringhurst** [comment]
Ah, that's a linker/rpath thing. Nothing is wrong with the plugin, just the options set when it compiles.

As a TEMPORARY fix, he could probably do something like 'sh configure && MACOSX_DEPLOYMENT_TARGET=10.5 make all' to get it working. Until I can figure out what's going on, I just replied to him with this so he can get things going.

**Comment by bringhurst** [comment]
Just opened https://github.com/chaos/slurm/issues/15 for the linker error so this pull request thread can rest in peace. :)

**Pull request merged**
