### PR TITLE
Feature/pmix ring rebased

### PR DESCRIPTION
**Pull request by adammoody**
Note that one commit had to disable building of the PAM plugin (comment: "disable contrib/pam ..."). I needed this because it was hardcoded to install to /usr/lib64, which prevented me from testing the pmi2 piece. You may want to restore this.

### CODE REVIEW

**Comment by grondo** [comment]
Some of the commit messages like "conditional compile" and "add some comments" could be improved -- however, if they are copied verbatim from upstream/schedmd repo then that is fine, no need to improve on their messages.

Other than that minor comment, this looks fine to me, pending a test of building, installing, and testing an RPM (seems like it will work fine, but might as well test before merging)

Also, can you just rebase and drop commit f18501e? You can do a rebase and force-push to this branch to update the current PR, no need to create a new PR.

Thanks!

**Comment by adammoody** [comment]
I compressed all of the small commits into two feature-level commits, plus @lipari 's commit on top.  How's this look now?

**Comment by adammoody** [comment]
This should now build on our system.  I don't think either of the above reversions are critical, but I'd still like to get @grondo 's opinion.

**Comment by grondo** [comment]
@adammoody, this is looking good. Has your branch been actually built on one of our systems? I'll check it out if not.

For 11fdc9c, can you reword the commit message so it says "drop call to slurm_get_auth_info in pmi2 plugin" then add in the actual commit message the details of why it was dropped (not in this version of slurm) and why it is safe to drop it (no auth_info will ever need to be passed to plugin auth creds for this version of Slurm)

Thanks!

**Comment by adammoody** [comment]
Thanks @grondo.  Updated the commit message.

**Comment by grondo** [comment]
Thanks @adammoody. I also found this branch doesn't compile on our TOSS3 systems. You may need to rebase on latest 2.3.3.chaos branch?

Also, I have a question about the strategy being used here. Will MPIs have to call the new `PMIX_Ring`  function to get a benefit from this addition, or does the PMI2 standard interface also use `PMIX_Ring` internally?

I don't think it will be a good approach to modify our local MPI libraries to call `PMIX_Ring` directly so I hope that is not the approach. Also we we want non-modified MPI and other PMI2 users to benefit from the fast startup you're providing here.

**Comment by adammoody** [comment]
The rebase fixed the compile error, so the latest PR builds now.  Let me test the functionality since it's been a while...

The SLURM PMI2 plugin implements both the PMI interface and the PMI2 interface using a tree of connections across the stepd processes.  This plugin enables more scalable startup for any MPI library using either PMI or PMI2.  Assuming this works correctly, we'll want to switch our system default MPI plugin from "mvapich" to "pmi2".

PMIX_Ring is a new method that I've added to the plugin to speed things up even further.  Whereas PMI/PMI2 execute an allgather that takes O(P) time for large enough process count P, PMIX_Ring executes a scan operation that takes O(log P) time.  To get that extra boost, the MPI library must be changed.  MVAPICH has integrated this capability.

**Comment by grondo** [comment]
> PMIX_Ring is a new method that I've added to the plugin to speed things up even further. Whereas PMI/PMI2 execute an allgather that takes O(P) time for large enough process count P, PMIX_Ring executes a scan operation that takes O(log P) time. To get that extra boost, the MPI library must be changed. MVAPICH has integrated this capability.

Is there no way to include this functionality in the standard PMI2 interface? As both a user and provider of PMI, Flux will want to take advantage of the speedup when launching under Slurm, but also if we modify local MPIs in such a way that they _require_ `PMIX_Ring` we wouldn't be able to run them under Flux. Is this `PMIX_Ring` symbol resolved dynamically somehow in MVAPICH?

**Comment by adammoody** [comment]
The goal is to add PMIX_Ring to the PMI standard as well as the new PMIx interface.

MVAPICH conditionally compiles in support for PMIX_Ring depending on whether the compile time constant HAVE_PMIX_RING is defined, which is specified in SLURM's pmi2.h as part of this patch.

**Comment by grondo** [comment]
> MVAPICH conditionally compiles in support for PMIX_Ring depending on whether the compile time constant HAVE_PMIX_RING is defined, which is specified in SLURM's pmi2.h as part of this patch.

Unfortunately that won't work for our use case, and it seems to thwart the purpose of PMI, which is to standardize the interface so a single MPI binary can launch under _any_ RM providing that interface. If `PMIX_Ring` isn't in the standard yet, wouldn't it be better if MVAPICH checked dynamically for the symbol using `dlsym()` or some other dynamic call (I'm not sure if PMI2 provides a way to query for extensions)?

**Comment by garlick** [comment]
Yeah, @trws and I were just chatting about this.  We really need our TOSS3 builds of MPI to follow the standard, such as it is.  As an aside, for us it's a _great_ development if you are building mvapich to use PMI2 instead of the PMGR stuff, which was great, but again problematic from an ecosystem perspective.

**Comment by adammoody** [comment]
I just tested the PMI2 plugin, and it worked fine on a simple 8-process, 2-node test.

Until we add PMIX_Ring to Flux and/or I add a dynamic check for PMIX_Ring, I'll build MVAPICH2 to use standard PMI2 calls.

**Comment by garlick** [comment]
Excellent, thanks. 

My feeling is PMIX_Ring needs to be either dropped from this PR or exported via an interface other than the canonical pmi2 one.

**Comment by grondo** [comment]
@garlick, good point. @adammoody, to get going with a new version of Slurm with your pmi2 backport, can we drop PMIX_Ring and move that immediately to another PR?

Is it possible to create a _separate_ libpmi2x.so with these extension functions? That would allow callers to attempt to dlopen the library for runtime detection of interfaces (We have to be careful about naming here, since presumable libpmix.so is already taken... libpmix2x.so might not be any better, I don't know.)

**Comment by grondo** [comment]
OK, since upstream Slurm already has `PMIx_Ring` anyway, and we're in dire need of @adammoody's fixes on new system hardware, I'm going to merge this.

In the meantime @adammoody, perhaps you can consider if the ring exchange support could be codified into the existing PMI2 interfaces? For instance, a fence could trigger setup of the ring automatically?

**Pull request merged**
