### PR TITLE
Job comment to db

### PR DESCRIPTION
**Pull request by lipari**
-- Renamed the Accounting Storage database's "DerivedExitString" job field to
    "Comment".  Provided backward compatible support for "DerivedExitString" in
    the sacctmgr tool.
 -- Added the ability to save the job's comment field to the Accounting
    Storage db (to the formerly named, "DerivedExitString" job field).  This
    behavior is enabled by a new slurm.conf parameter:
    AccountingStoreJobComment.

### CODE REVIEW

**Comment by dannyauble** [comment]
Don, when doing a new packing method, you need to copy the entire pack/unpack method to avoid missing something.  Please avoid just adding a line in the middle of the rpc pack/unpack.

**Comment by dannyauble** [comment]
Also, I am not sure the extra slurm.conf option is really needed.  I think it may just cause confusion.  I don't see much problem on always sending it.  But that is just MHO.

**Comment by lipari** [comment]
Danny, I made the comment sending optional so that we could turn it off when used with Moab.  Moab populates every job's comment field with attributes it can read back.
Regarding the packing/unpacking version clause, I thought that would help eliminate some redundant code.  I'm ok with creating a third version, though.

**Comment by dannyauble** [comment]
Ah, the option makes since then.  Perhaps it is the best way to go, but maybe have it work the other way, where you only set it if you don't want the comment stored?

When we started out doing multiple versions we were adding new options in this manor, but soon learned it was very difficult to keep things straight, and the code looked more spaghetti like.  While it does create redundant code. in the long run it is easier to read, and we know we don't mess up previous versions by creating a new copy and then add to it.  

Thanks for explaining your mentality on the patch.

**Comment by lipari** [comment]
A new pull request that incorporates the changes discussed in this dialog will follow...

**Pull request closed without merging**
